# Generated by Django 5.0.1 on 2024-01-30 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='trenging',
            new_name='trending',
        ),
    ]
